### ISSUE TITLE
CE Cross-domain access error

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/BackNode#17]
I tried to import a file with CE, but got this:
```
XMLHttpRequest cannot load http://localhost:6969/api/1.0/services/list. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://0.0.0.0:6969' is therefore not allowed access.
```
It's true that I'm accessing BN with http://0.0.0.0:6969 (as said in README). Tried with http://localhost:6969, it works well, but we should make a choice: 0.0.0.0 or localhost? Either we change the README or `data-ce-unifile-url='http://localhost:6969/api/1.0/'` in index.jade. Or allow cross-domain XHR, but I think we'll get some security issues.

Minor issue, but it can't ruin the first experience on BN, it would be a shame.

**Comment by RonanDrouglazet** [comment]
Yeah, lexoyo have the same issue the first time, but i've forgot that.. i think in first we should just change the README, simpliest solution :) 

Then maybe put a dynamic var for data-ce-unifile-url ! 

Ok for you ?

**Comment by JbIPS** [comment]
Fine by me :). I'll change de README and make a PR as soon as I've got something to show for the text editor (tonight I hope).
