### ISSUE TITLE
Make images editable

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/BackNode#2]
BN needs to parse HTML page to find nodes with attribute "data-bn" equals to "image".
Those nodes should listen to mouse over, which show a visual alert for modification, and to click, which open an upload menu to change the source.

**Comment by JbIPS** [comment]
If this one's free, I'm gonna take it. Any advice/idea before I start?

**Comment by lexoyo** [comment]
Well there are several ways to edit an image: Browse for a new image withe cloud explorer, edit with pixlr like in silex, maybe add a URL?

And also I believe an image can be an img tag or a background image

**Comment by JbIPS** [comment]
I was going for a CE based solution for content images (= img tags). I think CMS is about content, not design, so we'll let UI customization to Silex ;).

I'll start with that, and we'll progressively add sources for image edition (I like the URL one)

**Comment by RonanDrouglazet** [comment]
i think we should finish text editable before all :) i found several bug on it, i've start to fix that, like switch off editable not done, text edition tools miss placed (hover the text for me) etc...

i work on switch off editable, but we have to see if you have the same bug as me for CKEditor hover the text

**Comment by JbIPS** [comment]
Editor looks OK for me (on lastest version on my branch) ![capture d ecran 2015-01-13 a 13 36 22](https://cloud.githubusercontent.com/assets/2248473/5720774/3a650128-9b29-11e4-8410-28e8f27a8b62.png)

**Comment by JbIPS** [comment]
Just pushed a [commit](https://github.com/JbIPS/BackNode/commit/bbb1415e4bb2a8a115bce9b2b3ce3166eb503a5d) that add a nice border around editable text and a very light "switch-off", hope it doesn't collide with your dev @RonanDrouglazet

**Comment by RonanDrouglazet** [comment]
Ok thanks a lot ! i will test your branch tonight, i just try on BackNode master branch :)

sorry this week i was not a good contributor...i have a lot of things to do on other projet, but this will change tonight and the rest of week ! i hope so..

**Comment by JbIPS** [comment]
You were a bad, baaad contributor ! XD
We're here to have fun (at least me), so don't put yourself under pressure :+1:

**Comment by RonanDrouglazet** [comment]
you're right ! :+1:
