### ISSUE TITLE
Attribute names

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/BackNode#24]
At this moment we use `data-bn` with the type of content to mark editable elements on the HTML page. The problem is we'll have to consider a lot of type: text, img, link, video and it will keep growing. Second problem is that this type is redundant with the tag of the element.

I'm thinking we could just use a "editable" attribute (`data-bn-editable="true"` or `data-bn="editable"` or anything else). This will allow us to treat every edition request almost the same and just use a switch on tag name for special needs.

What do you think of that @RonanDrouglazet & @lexoyo ?

**Comment by lexoyo** [comment]
I like the css classes for this kind of uses but data-* is fine too
If we use ```data-bn-editable="true"``` then simply ```data-bn-editable``` is fine

**Comment by RonanDrouglazet** [comment]
:+1: you are totally right
