### ISSUE TITLE
Clean up output HTML

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/BackNode#29]
When saved, the outputted HTML show duplicate headers and lots of useless attributes. I think what we should aim to is the same HTML the user gave us but with some modification in the content of the editable node.

**Comment by lexoyo** [comment]
See these lines in Silex code to cleanup HTML before saving it (will only make it readable)

* [the library](https://github.com/lexoyo/Silex/blob/master/dist/client/libs/beautify-html.js)
* [its use](https://github.com/lexoyo/Silex/blob/master/src/js/model/file.js#L319)
